[package]
name = "boundrs"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.34", features = ["serde"] }
eframe = { version = "0.34", default-features = true }
egui_extras = { version = "0.34", features = ["all_loaders"] }
image = { version = "0.*", features = ["jpeg", "png"], default-features = false }
# Add the types you want support forpalette = "*"
alphanumeric-sort = "*"
glob = "*"
anyhow = "*"
serde = { version = "*", features = ["derive"] }
toml = "*"
clap = { version = "4.6.1", features = ["derive"] }
csv = "1.4.0"
log = "0.4.29"
itertools = "0.14.0"
linfa-clustering = "0.8.1"
linfa = "0.8.1"
ndarray = "0.16"
env_logger = "0.11.10"
sv-datasets = { git = "ssh://git@github.com/spadesvision/blackjackeye.git", branch = "main" }
sv-detections = { git = "ssh://git@github.com/spadesvision/blackjackeye.git", branch = "main" }
# sv-datasets = { version = "0.1.0", path = "../blackjackeye/spades-rs/sv-datasets" }

[profile.release]
debug = true
